# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
#org.gradle.configureondemand=true
fabric.loom.dropNonIntermediateRootMethods=true

# Mod properties
mod.version=1.3.0
mod.group=cc.cassian
mod.id=villager-trading-plus
mod.name=Villager Trading Plus

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]

# Mod setup
deps.mixin_extras=0.5.0
deps.fabric_loader=0.18.4
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]

deps.kaleido=0.3.3+1.3.2

# Publishing
publish.modrinth=fRhq4ueb
publish.curseforge=1107609