mod.mc_dep_forgelike=[1.21.11, ]
deps.minecraft=1.21.11

deps.neoforge=21.11.3-beta

deps.cloth_version=20.0.148
deps.jade_version=17.1.2+neoforge
deps.wthit_version=14.0.1
deps.badpackets_version=0.8.1
deps.forge_config_api_port=21.8.0
deps.fast_item_frames=EbbG9L7V
deps.puzzles_lib=3Q61n79f
deps.glowcase=1.9.0+1.21
deps.placeholder_api=2.5.2+1.21.3
